### ISSUE TITLE
录音转写

### ISSUE THREAD

**Issue by CastleStar14654** [PoaceaeTriticum/Exposure_HongSenlian#11]
本转写为使用科大讯飞自动生成，并（大部分）经本人手动校对，本人在此放弃对其所有著作权声索、并将其转让与本仓库所有者。

# 编辑记录
2022-07-12：隐去部分未处理的姓名；添加版权相关声明。

# 录音转写

所有的第三人称代词使用的性不一定正确。部分录音暂未校对。当事人或其他人的姓名有消音，用【】代替。

- [6.12洪森炼自述（关于电动车）01](#612洪森炼自述关于电动车01)
- [6.12洪森炼自述（爬山）01](#612洪森炼自述爬山01)
- [6.12洪森炼自述（爬山）02](#612洪森炼自述爬山02)
- [6.12洪森炼自述（爬山）03](#612洪森炼自述爬山03)
- [6.12洪森炼自述（爬山）04](#612洪森炼自述爬山04)
- [6.12洪森炼自述1](#612洪森炼自述1)
- [6.12洪森炼自述2](#612洪森炼自述2)
- [6.12洪森炼自述3](#612洪森炼自述3)
- [6.12洪森炼自述4](#612洪森炼自述4)
- [6.12洪森炼自述5](#612洪森炼自述5)
- [6.12洪森炼自述6](#612洪森炼自述6)
- [6.12洪森炼自述7](#612洪森炼自述7)
- [6.12洪森炼自述8（关于性骚扰）](#612洪森炼自述8关于性骚扰)
- [6.12洪森炼自述9](#612洪森炼自述9)
- [6.12洪森炼自述10](#612洪森炼自述10)
- [6.12洪森炼自述11](#612洪森炼自述11)
- [6.12洪森炼自述12](#612洪森炼自述12)
- [6.12洪森炼自述13](#612洪森炼自述13)
- [6.12洪森炼自述15](#612洪森炼自述15)
- [6.12洪森炼自述16](#612洪森炼自述16)
- [6.12洪森炼自述17【未校对】](#612洪森炼自述17未校对)
- [6.12洪森炼自述18](#612洪森炼自述18)
- [6.12洪森炼自述20【未校对】](#612洪森炼自述20未校对)
- [6.12洪森炼自述21](#612洪森炼自述21)
- [6.12洪森炼自述23](#612洪森炼自述23)
- [6.12洪森炼自述25【未校对】](#612洪森炼自述25未校对)
- [6.12洪森炼自述27](#612洪森炼自述27)
- [6.12洪森炼自述28](#612洪森炼自述28)
- [6.12洪森炼自述30](#612洪森炼自述30)

## 6.12洪森炼自述（关于电动车）01

+ hsl 00:00  他坐在电动车后面，我把他载回去了。

## 6.12洪森炼自述（爬山）01

+ hsl 00:00  我【】单独出过门吗？
+ 问话 00:01  对。
+ hsl 00:02  有吧，有一次。

## 6.12洪森炼自述（爬山）02

+ 问话 00:00  因为我知道你们不只去了一次。
+ hsl 00:02  对。
+ 问话 00:03  你说你去了哪里。
+ hsl 00:04  但我们干坏事吗？没有吧？一次都没有，一点点都没有。
+ 问话 00:08  你们去过几次？
+ hsl 00:09  我……我不管，我——
+ 问话 00:11  你刚才说去了一次，现在你又不管去了几次，你到底去了几次。
+ hsl 00:14  我现在跟你说，你现在这个事情。
+ 问话 00:18  你看看你这个事情——
+ hsl 00:19  你有——
+ 问话 00:20  你说的话里面全部都是漏洞。

## 6.12洪森炼自述（爬山）03

+ hsl 00:00  然后，我、我、我如果说，我觉得我跟【】关系很好，但是因为他有的时候比如说情绪比较失控，我就会他也不是不爱运动。好，我就我，他因为睡眠不好，我说我带你去，因为有两天我比较烦躁，他也比较那个，所以我们两个去爬了山，但是，绝对——
+ 问话 00:23  你们两个去爬了山？
+ hsl 00:24  对。我带他，我还，他比我厉害，他比我先到，因为我们当时一起的还有3个、还有4个人，三个男的一个女的，但是——
+ 问话 00:33  都是谁？
+ hsl 00:34  那个不认识，是山友。
+ 问话 00:36  好。
+ hsl 00:36  那个是这样子的。
+ 问话 00:37  那么就是说你和【】——
+ hsl 00:39  后来
+ 问话 00:39  ——一起去爬了山。
+ hsl 00:40  后来我先跟你说，后来我觉得这个不太好。

## 6.12洪森炼自述（爬山）04
+ 问话 00:00  我们既然刚才说到爬山的，我们不妨多说几句。爬的什么山？
+ hsl 00:05  你陪他去爬到什么山喏？他跟我说他当时跟去自己跑去房山那边爬的，我说你不用去跑房山那边了，你们去过爬房山那边的山吗？要叫他坐车坐好久。
+ 问话 00:19  房山的山{不清}，你们爬的什么山？
+ hsl 00:23  我们就在五环上那边。
+ 问话 00:26  五环上是什么山。
+ hsl 00:27  那就百旺百望山出去一点点。
+ 问话 00:29  来望山出去一点点是什么山？
+ hsl 00:30  我不记……我记不住。
+ 问话 00:32  查一下。有聊天记录吗？查一下。
+ hsl 00:34  不不不，我们、我们不管这个事儿。
+ 问话 00:38  那这样吧，山离这儿有多远。20公里。你们怎么去的？
+ hsl 00:47  开车去的呀，但是绝对没有任何侵犯的行为啊。
+ 问话 00:53  开车去的，你们两个人？
+ hsl 00:54  对。
+ 问话 00:56  你什么时候？工作日吗？
+ hsl 00:58  记不得了，应该是……应该是某天的下午。
+ 问话 01:02  一个工作日的下午，一个老师带着自己的女——男老师带着自己女学生去爬山。
+ hsl 01:08  对。
+ 问话 01:09  你开车的时候你让他坐在哪里？
+ hsl 01:16  我们、我们所有的学生啊，只要是跟我跟车的，因为我后面有安全座椅，他们都是在前面。但是我们绝对没有任何的手超过中线的，绝对没有，可以百分之百保证。
+ 问话 01:31  那你们爬山爬了几次。
+ hsl 01:33  我记不得了，一次还是两次。反正有一次是那个堵车堵得比较狠，然后我还在，上次可能是你的电话吧，我还说你接啊。
+ 停顿 01:45 。
+ hsl 01:45  不，有一次6点多钟，因为堵车堵得比较紧，因为从清河那边回来的。因为当时从、就是圆明园那条路比较堵，我从清河那边走走高速回来的。中间6点多钟有一个人给他打电话，我说你接啊。然后后来回来的时候，不是回来的时候放下来嘛，放下来的时候我们绕过去从妇幼那边回来的。他后来我在北航那边把它放下来。北航那边我还跟我还摇下车窗跟他说：“【】你回去的时候告诉我一声。”因为我是一个人带他出去的嘛，带他出去我又把他带回来的，他、他在北航下了车，他说他去找同学吃饭。
+ 问话 02:28  那请你告诉我你为什么两次爬山都只带【】一个人呢。
+ hsl 02:32  我当时想叫【】来这的啊，我两次都想叫【】来的啊。我后面还跟他俩讨论了，我说下次的话你就可以叫【】了。然后而且我们有一次没爬完，第二次是爬完了，爬完的时候我们同时跟我们一起爬的有4个人，3个男生1个女生。
+ 问话 02:53  不是说你同时爬的有3个男生，1个女生。你作为1个老师男老师，你为什么要在工作日的下午叫上你的女学生去爬山，你知道他不敢拒绝，而且你只叫他一个人，你为什么只叫他一个人？
+ hsl 03:05  不不不，不不不。原因是什么呢？如果这件事情我做错了，我下次再也不做了。因为原因是因为什么？我跟你说了很多遍了，【】他每次晚上失眠。如果说他觉得这个是我的问题，我们两个在这方面可能我们就错节了，真的错节了，真的错节了，ok。

## 6.12洪森炼自述1

+ hsl 00:00 就我在门口把他拉就在那个楼梯口，我抓着他的手。
+ 问话 00:05  抓着他的手。
+ hsl 00:07 对抓着他的手，然后……
+ 问话 00:10  然后呢？
+ hsl 00:10 然后后来他就，我就说你不走，因为【】已经去给他买蛋糕去了，就拿回来，然后后来我就把他留在上面，然后他就去厕所，然后后来我下去安抚其他学生去了，然后我就把【】【】叫上来，他们两个就在楼梯口聊了一会儿，然后后面就是、就是没有什么，然后后面下去过后，就是大家跟他过生日，过完生日过后他就上来拿包，拿完包过后，然后我们俩就是一起出去，出去过后就是走到楼梯门口，就走到那个学校门口，不是学校门口，就是在这个楼的门口嗯，然后我们两个就聊了一会儿，然后聊课题就是这个课题。课题过后我就把，因为很晚了，所以说我就把它送到和寝室的门口，我们两个还在门口，就是就这个课题他不是要答辩嘛，然后从头我跟他说了一下三个思路，就把它扩开一点，然后就没有了。

## 6.12洪森炼自述2

+ 问话 00:00  你再想想你把他带到办公室，两人你干了什么？
+ hsl 00:02 我啥都没干啊。我就安排了一下，
+ 问话 00:07  你啥都没干？
+ hsl 00:08 对啊。
+ 问话 00:08  你就在这啥都没干？
+ hsl 00:10 我就在这啥都没干。
+ 问话 00:12  你刚才还说你拉了他到门口，你这回你又承认你在办公室里了。你看看。
+ hsl 00:17 不是，我是拉着他这个时候，而且他是穿着衣服的，因为他要走啊，要跑。

## 6.12洪森炼自述3

+ hsl 00:00 那个，昨天的情况就是把【】失控了，然后我把【】带到这个办公室，然后我啥都没做，我就去到隔壁去拿了包了10瓶可乐，我们同学还在跟我说呢，我说我下去了，我就安抚他们，我说我包的是，隔壁包了10的那个小瓶的这个可乐，这样往下去跟同学们过生日。然后，那个不放心，就是【】因为我让【】再上来，因为我说他在我办公室冷静一下，但是冷静一下这个门是开着的。

## 6.12洪森炼自述4

+ hsl 00:00  我把他就在门口，因为他跑出去了，我离他最近我就抓住他过后，我说你在这休息一下，然后我就出去了。

## 6.12洪森炼自述5

+ hsl 00:00 他，她从进到这个房间，我安抚她情绪最多不到、到两句话。
+ 问话 00:05  这两句话你干了什么？
+ hsl 00:08 不是——
+ 问话 00:08  你说你说的哪两句话，你说。
+ hsl 00:10 我啥都没干。
+ 问话 00:11  你说你说的哪两句话。
+ hsl 00:11 我啥？我就说对不起啊，那个那个你【】她的生日那也是我有过错。我说你不能，我不能，我觉得你不应该怪【】。我说至少我还在兜底，我说这个事如果要认错的话是我应该认错。那我安抚他我有错吗？而且昨天那个情况很、很那个。好，你如果说觉得我做错了，那就是我在楼梯口就是、就是拉着他的手了。
+ 问话 00:41  不是，不是拉着他的手。你说，你说的是哪两句话了？你就说你在这个房间里说的哪两句话，你刚才已经说了五六句了，你说的哪两句？
+ hsl 00:50 就两句话。
+ 问话 00:51  两句？
+ hsl 00:51 我当时跟他说，我说你如果说。第一句话，我说你不能走，是因为师兄【】已经去给你拿蛋糕去了。
+ 问话 00:59  一句。
+ hsl 00:59 对，第二句话我就说的，这件事情你不能怪【】，【】因为他生病了，我上周他的耳朵是不行的，还有其他方面是不行的。然后你也不能去怪他，因为如果这件事情有错我也有错，因为【】的生日我是记得的，我提前问了他。但是【】生日我理论上也是记得的，我记得是5月份，但我记不得是哪一天。然后就是这么一个过程——
+ 问话 01:28  这是几句话了？
+ hsl 01:30 不，就两件事情啦，我坐在那个椅子上跟他说的。
+ 问话 01:33  你坐在那个椅子上？
+ hsl 01:34 就那个椅子，他坐在这边，这边。
+ 问话 01:36  我们来比一比你坐在哪个椅子上。\[大量摩擦声\]现在我是【】，你是怎么带他进来？
+ hsl 01:43 就直接进来的呀。
+ 问话 01:46  我们先从外面来。怎么拽着他上来的？来，拽着我。\[大量摩擦声\]
+ hsl 01:56 对他的包在这。然后我就在这。
+ 问话 02:05  然后呢，你在这儿做了什么？
+ hsl 02:07 然后，对。啥都没做啊，真的啥都没做，前后才就——不是，我首先，你先听我说。我们现在【】我们从出来上来就几分钟的时间，两两两三分钟。
+ 问话 02:25  到底在哪里？
+ hsl 02:35 就在这儿。【】就在这儿，我。
+ 问话 02:37  你刚才还拽着我的手机都拽到那里，现在又说你在这儿，【】在这儿。你这不是满口谎话颠三倒四吗？

## 6.12洪森炼自述6

+ hsl 00:00 因为跟【】一起上来最多不到一分钟。

## 6.12洪森炼自述7

+ hsl 00:00  而且唯一的一个跟我一起上来的也联系不上。

## 6.12洪森炼自述8（关于性骚扰）

+ hsl 00:00 他说我对我们的女学生都有这个，都有性骚扰，我不知道。
+ 问话 00:05  你看我从来没有提过性骚扰，这个词，这个词是他自己说的。
+ hsl 00:09 嗯？！你刚刚在楼下，你你你，你记清楚啊。
+ 问话 00:10  我一句性骚扰的话都没说。
+ hsl 00:13 你说你对女学生是是什么什么，你刚刚在楼道。
+ 问话 00:15  我绝对没提这三个字。
+ hsl 00:17 不不不，我没想说了，我不跟你说，我不跟你说，我跟你、我跟你说清楚了。

## 6.12洪森炼自述9

+ hsl 00:00 我就记得我说了两个意思，一个是你……
+ 问话 00:03  互联网这边。
+ hsl 00:03 走了这个怎么办？就就这个权责怎么办？第二个事情我说，我已经很宠着你了，你在这里面我没有觉得你不应该这样子，对吧？第二个是，那个我觉得如果说是我们谁的过错的话，应该不是【】的过错。
+ 问话 00:18  这两句话跟刚才呢又不太一样。

## 6.12洪森炼自述10
+ hsl 00:00 因为昨天，我我我，我也没有失态，因为我拉的是【】的……手臂
+ 问话 00:06  她没有失态，她是故意的。
+ hsl 00:08 我拉的是【】的手臂，没拉——

## 6.12洪森炼自述11

+ 听不出是谁 00:00 让谁去拉他们，你们当时没动。

## 6.12洪森炼自述12

+ 问话 00:00  （笑）你自己说是性骚扰，我可没说是性骚扰。
+ hsl 00:02 不不\[数秒听不清\]你现在，你现在。

## 6.12洪森炼自述13

+ hsl 00:00 那现在这个事情，你们，你们就说要怎么弄？我我现在，你昨天。好，如果说有一些捕风捉影的话，那我们来，你们的意图是什么？先说。

## 6.12洪森炼自述15

+ hsl 00:00 我我，（叹气）我去拉他的时候我还是很注意的。我是拉着手，手臂还是手腕，我没拉手。

## 6.12洪森炼自述16

+ 问话 00:00  其实也不是说跟你——
+ hsl 00:01 也不会留你也不会强求你。我们这件事情，我不会是让他这些事情出现在(听不清)上。如果你——
+ 问话 00:09  为什么不会让别人变另外一点。
+ hsl 00:11 不，我我我尊重你的任何决定，但是我也让你放心。我们在这儿这个门随时会开着。说实话，如果我们确定你们在，如果包括高涛来跟我说，那这个事情确实是有不对的地方了，那我马上，我们来处理这件事情。但是如果说【】希望这么处理，那我们再来处理。

## 6.12洪森炼自述17【未校对】

+ 说话人1 00:00 你和人在不好意思，你在办公室独处的两分钟，你自己说是两分钟。
+ 说话人2 00:08 应该差不多两三分钟，有三分钟吗？会。
+ 说话人3 00:13 不清楚你是什么时候让他上来的，就出去那会儿应该有五六分钟。
+ 说话人2 00:18 对出去那会有五六分钟。
+ 说话人4 00:21 对我就上来过后。
+ 说话人2 00:24 然后我让他冷静一下，他就没管他，然后我就去宋老师拿可乐去了。因为我想说说既然没给他定了大蛋糕，我们给他我去拿脚里面烤了，大家一起给他过个生日，我不知道我昨天做什么事，昨天的生日我已经很尽力帮他了。
+ 说话人1 00:50 又是一个版本，总之洪老师的版本里都没有在办公室，关键的两分钟。
+ 说话人4 00:55 两分钟我已经说了，说我跟他的内容说了三个点两个点，一个是我觉得没有错，如果这个蛋糕没有买，他说他应该有，如果我昨天会限制。
+ 说话人2 01:09 我早知道会限制你这种情况的话，我昨天就让他走了，我们大不了我们自己吃那老不就完了。
+ 说话人1 01:16 对昨天你让他走也就没事了，你要把他拉进办公室来干什么？来满足你的禽兽之心吗？
+ 说话人2 01:22 我哪有了这禽兽。
+ 说话人4 01:26 你说话不要这么样整合。
+ 说话人1 01:28 我这已经很克制了，我说话已经很克制了。

## 6.12洪森炼自述18

+ hsl 00:00 但是我告诉你，你转告【】，如果中间有问题。
+ 问话 00:06  事实上就是中间有问题。
+ hsl 00:08 如，你就说，如果他觉得中间有问题。
+ 问话 00:11  不是他觉得中间有问题。每一，明天每一个中国人每一个全世界的人，他都都能看出来中间有问题。
+ hsl 00:18 好好，如果有问题，那你就提前我跟他说对不起，好吧？如果说他误解了，或者说是不是。
+ 问话 00:25  误解这种事情，怎么可能误解。
+ hsl 00:26 不不不，我们。
+ 问话 00:29  你把女性当做什么了，这种事情怎么可能误解呢？
+ hsl 00:32 唉哟。

## 6.12洪森炼自述20【未校对】

+ 问话 00:00  而且我当，当我听到洪老师又来这天马行空，我不承认的时候，其实我难言我的愤怒。好。
+ 说话人2 00:14 \[大量摩擦声\]
+ 问话 00:31  反正怎么说呢，没有拜天就说不是了。
+ hsl 00:35 那个，这个无所谓了。你你你，如果你觉得我有动作姿态，或者说有其他的不对的地方，我说一声。这个，还有你也放心，我。
+ 问话 00:59  那我们这样说，你觉得你有没有动作姿态或者不对的地方。
+ hsl 01:03 我确实比较cong——

## 6.12洪森炼自述21

+ 说话人1 00:00 如果昨天我拿他的手我也考虑了。
+ 说话人2 00:05 是不是太不是拿他的手是另一个动作，你自己知道心里清楚是什么东西。
+ 说话人1 00:11 如果说我让他冷静下来，那个冷静下来，我当时真不清楚，因为当时他一直比较激动，我当时也让。
+ 说话人2 00:20 他两年下来是什么动作。
+ 说话人1 00:22 我不知道。
+ 说话人2 00:23 你不知道你可以演示一下怎么让人冷静下来，你是用了什么动作让人冷静下来？
+ 说话人1 00:30 不，我们现在来说这个问题好，我没有侵犯，我可以明确告诉你，如果说我也可以明确告诉你。
+ 说话人2 00:42 你这个侵犯是怎么个定义叫做侵犯。
+ 说话人1 00:45 我觉得我没有有暗示性的动作，也没有暗示性的行为去说，因为你刚刚已经说到这个问题了，你说对你询问问题，我可以给你明确的说。
+ 说话人2 01:09 这个应该没有没有还是有可能有没有没有什么。
+ 说话人1 01:17 没有侵犯女生人生的这个动作。
+ 说话人2 01:22 听上你这种人生什么样的动作，你觉得算是听上去的人生？
+ 说话人1 01:26 不，我就问你你定义的你说你觉得有问题的，如果若璇觉得我们有问题，因为昨天那个事情确实比较突然，然后我跟他说了一句话，我说我说你来的时候我我已经基本上都是比较宠你了，因为我一直跟他说。

## 6.12洪森炼自述23

+ hsl 00:00 我就改成我们全组的，去运动。去运动是打乒乓球，【】打乒乓球打得比较好。好，我们就打两个小时乒乓球，大家都在，然后羽毛球的话【】不擅长那就走了。但是打篮球他去过一次，打篮球他去过一次，因为【】篮球运动还是挺比较积极的，他跑动也比较积极。如果说在那个地方，因为我跟夏老师组的女生叫，另外一个他防守更那个一些，但是【】我记得只有一次，我撞到了他，然后我把他拉起来了，在他倒下之前拉住了他。好，如果所有的肢体接触，这个是，这个是我能告诉你的。
+ 问话 00:46  不能告诉我的呢。
+ hsl 00:47 不是，我所有的该告诉你的，但是——
+ 问话 00:52  据我所知还有很多该告诉我的，没有告诉我。
+ hsl 00:56 不，我先跟你说。如果说这个事情，对若旋造成了伤害，或者说我们，对你也造成了伤害。
+ 问话 01:03  不是对我造成了伤害。我作为一个男性，其实我们认为是对女性造成的伤害。就是说不没有关，但是你说说这个观念有问题，不过我……我们来谈事实吧。
+ hsl 01:18 我就跟你说这个事情。你希望怎么处理。你告诉我一下。

## 6.12洪森炼自述25【未校对】

+ 说话人1 00:00 不，我先跟你说另外一件事情，我们都是北大的。
+ 说话人2 00:04 我很引以为耻，好。
+ 说话人1 00:07 你如果觉得我是你的耻辱，我谢谢你好，为什么要谢谢？不？但是我们都不能尽量不要让北大两个智能修。
+ 说话人2 00:18 不是要北大，我们为什么要维护北大的声誉，就是要把错误的事情，不对的事情，北大所允不允许的事情，要把它从北大剔除出去，这才是我们维护北大的城市可以有另外一种做法，就比如说。
+ 说话人1 00:35 去学院的纪委直接说就行了。

## 6.12洪森炼自述27

+ 问话 00:00  这样。你承不承认？
+ hsl 00:02 我不承认我对【】有非分之想。

## 6.12洪森炼自述28

+ hsl 00:00 现在你觉得为了我一个hsl去玷污北大有值得吗？
+ 问话 00:04  不是为了你一个hsl就见我是为了北大，我要你自己，那行我要去捍卫北大的纯洁。
+ hsl 00:13 但是我告诉你啦，这种方式。因为现在对舆论，他是说不清楚的，你明白吗？
+ 问话 00:22  但是我说的非常清楚。
+ hsl 00:26 我现在也\[听不清\]好，我相信，因为我现在回忆了一下。我跟【】的相处，确实有时间。

## 6.12洪森炼自述30

+ hsl 00:00 我就是告诉你，如果你觉得【】这件事情，我【】对【】造成伤害，或者说我我我们现在就建立起严格的界限，就是【】，我还是那样子。

**Comment by CastleStar14654** [comment]
可能的有确定性的继续方向：
1. 是否能证明他在6.11拖当事人上了楼梯，比如监控。
2. 是否有人证证明多次在组会后留下当事人。

**Comment by luoy80** [comment]
请问是否可以对内容进行搬运？
（会注明出处及链接）

**Comment by CastleStar14654** [comment]
@luoy80 本转写为使用科大讯飞自动生成，并（大部分）经本人手动校对，本人在此放弃对其所有著作权声索、并将其转让与本仓库所有者。请联系本仓库所有者。
