### ISSUE TITLE
已澄清 

### ISSUE THREAD

**Issue by jiangjiangyi** [PoaceaeTriticum/Exposure_HongSenlian#13]

**Comment by jiangjiangyi** [comment]
localcrimenews.com搜索senlian hong 即可看到 不知道有没有用

**Comment by AmilyFox** [comment]
https://www.localcrimenews.com/welcome/detail/31476652/senlian-hong-arrest.html

**Comment by AmilyFox** [comment]
![This is an image](https://myoctocat.com/assets/images/base-octocat.svg)

**Comment by AmilyFox** [comment]
![This is an image](https://obohe.com/i/2022/07/11/12vbjmh.png)

**Comment by AmilyFox** [comment]
![This is an image](https://obohe.com/i/2022/07/12/tgjvb.png)

**Comment by jojo23333** [comment]
我擦 年龄履历都对上了，还真是他 ，建议作为证据pull request
![image](https://user-images.githubusercontent.com/19428666/178325116-5466f2da-6d09-40a7-a02b-d8bef281c432.png)
![image](https://user-images.githubusercontent.com/19428666/178325315-4f92666f-f287-426d-8af5-a6b21cfc32cd.png)
![image](https://user-images.githubusercontent.com/19428666/178325636-5146ffb0-da09-45ce-b4a8-932d73ea508d.png)

**Comment by jojo23333** [comment]
@AmilyFox Can you provide the link to your second uploaded screenshot here?

**Comment by lydialin92** [comment]
洪森炼和他太太在圣迭戈多名共同的好友，在北大圣迭戈校友群里证实，起码这次拘留/逮捕是个误会，与这次的事件没有什么关系。

**Comment by jojo23333** [comment]
@lydialin92 哈喽，请问有校友群聊天记录截图嘛，clarify的证据也可以发在这里

**Comment by lydialin92** [comment]
> @lydialin92 哈喽，请问有校友群聊天记录截图嘛，clarify的证据也可以发在这里

因为这个事情涉及到洪森炼妻子的隐私，所以请大家不要再深挖人肉，伤害其他人。就事论事，不要因为这个记录对这次事件进行有罪推定。

![Screenshot_20220711-220434_WeChat](https://user-images.githubusercontent.com/109121505/178412341-b826a6af-2901-4c21-9540-1a144789dbf1.jpg)

**Comment by wondefullife** [comment]
原来 GITHUB 用来收集证据也是个不错的选择呀

**Comment by wondefullife** [comment]
这个说法合理吗，如果是个误会的话，虽然没被撤销犯罪记录，但也没登记释放日期、保释金

**Comment by lydialin92** [comment]
洪并没有被arrest, 只有被detention, 谈不上释放和保释。可以查加州的审判与上庭纪录，并没有洪，所以目前证据来说洪从来没有被定罪。另外，localcrimenews并不是犯罪记录，而是出警记录，具体可以看这里的解答https://www.quora.com/How-does-local-crime-news-obtain-address-information-for-people-who-have-been-arrested

**Comment by AmilyFox** [comment]
谢谢各位朋友的证据和求实。这些截图都来自localcrimenews的数据，只是作为一个参考，不具有法律效力。希望大家都能够理智看待。无论如何，事实至上，真理至上，当事人的朋友们一定会遵循这些法则帮她维权到底。
