### ISSUE TITLE
录音处理不完全，暴露了相关人的信息

### ISSUE THREAD

**Issue by Alicesla** [PoaceaeTriticum/Exposure_HongSenlian#14]
6.12洪森炼自述10 可能出现了相关人的名字，感觉可以再处理一下

**Comment by lydialin92** [comment]
建议将录音移除，留下转写文本，或者更精细的消音。否则录音中没消干净的信息，加上已知的课题组，北大，转导师等信息，太容易暴露受害者姓名。

**Comment by AmilyFox** [comment]
好的，非常感谢您的建议！
