### ISSUE TITLE
向各位同学报平安&一些录音(转载)

### ISSUE THREAD

**Issue by PoaceaeTriticum** [PoaceaeTriticum/Exposure_HongSenlian#3]
我是原楼主的朋友，她现在是安全的。我要在此替她深切地感谢大家的关心，同学们的支持给了她很大的鼓励。正如她所说，过去的事情已经无可挽回，但她可以选择说出来，让自己成为最后一个受害者。她一定会坚持到底，让人渣导师不再有下一次的机会。
我看到一些网友想要看更进一步的材料，因为她的精神状态不太好，所以由我整理了一部分提交给医学部纪委的材料和录音放在下面。录音来自6月12日受害人指认洪森炼后洪森炼本人的谈话。因为涉及到受害人及其同学的名字，所以我们对一些音节做了消音处理，花了一点时间。还有更多的录音正在处理中。
作为朋友，我很钦佩受害人的勇敢，因为她确实为了指认洪森炼豁出了一切。我知道，她是为了维护自己的尊严，同时也为了不让后来者重蹈覆辙；但我很难想象，将自己的屈辱、痛苦分享给千万人，这需要多大的勇气。如果没有这些事情，她本可以顺利地毕业、深造，我想她不可能像个别网友所猜测的那样有编造的动机。
以下是当时提交给纪委的材料节选。更多内容还在整理当中。

二、以课题讨论的名义创造猥亵机会1.安排大量的、不必要的讨论此外，洪森炼每周会安排两次组会，周三晚上是有我参加的小组会（有实验室一半同学参加），周六晚上是大组会。每次组会结束后，洪森炼都会留我再次与他单独讨论。虽然每次组会都会有很多同学一起参加，但他绝大多数时候都只留下我讨论，而且只留下我一个人。此时会议室里的其他同学都回去了，明明可以在会议室讨论，但是洪森炼每次都要坚持要我跟他前往他的办公室。组会每次的结束时间都已经是十点或者十一点之后了，所以我每次结束与他的单独讨论往往都到了十二点之后。而且，洪森炼每周找我讨论这么多次，真的有这么多和科研相关的事情吗？不是的。事实上，在洪森炼每次以讨论课题的名义要我去他的办公室讨论时，他大部分时间都在讲一些与课题毫无关系的事情，尤其爱讲一些恶劣事件，诸如上文所述的权色交易、色利交易，真正讨论课题的时间反而很少。我对他的这些故事完全没有兴趣，但又不敢走。洪森炼每一次讨论结束后都要求我坐他的电动自行车送我回去，然而从国重楼到宿舍楼不过五分钟的步行路程；洪森炼多次要求我把手扶在他的腰上，我都强烈拒绝并将手放在车座后背上。【6.12洪森炼自述（关于电动车）01】每次去找洪森炼讨论或者开组会，都成为了我的噩梦，我每次都要做好十足的心理建设，并且把要去讨论的时间告诉我的男朋友才敢去找他。 2.反锁门每次我和洪森炼单独在办公室讨论，他都要先将门反锁。在我刚刚换导师成为他的学生时，他还以他的门坏了关不上作为理由，后来他的门修好了，他仍然每次反锁办公室的门，甚至都不再找理由了。现在想来，一般老师和学生讨论的时候，尤其是男老师和女学生单独讨论的时候，都是开着门的。在之后与药学院工作组的谈话中，工作组的老师也指出，药学院有规定要求导师与学生在办公室讨论必须开着门。洪森炼不仅不开门，还要将门反锁，他确实是在为他的猥亵行为做准备。后来在我和实验室同学的交流中，一位同学告诉我，她有几次想在洪森炼和我讨论时进洪森炼的办公室，因而她也发现了洪森炼总是在和我讨论的时候反锁房门。

 3.要求我晚上出来在校园陪他逛

5月24日，洪在晚上22:29，要求我出来与他在校园里边逛边讨论。
 4.要求我单独跟他开车去买花

2021年11月10日，有一次我和他讨论结束之后，洪森炼突然要求我陪他出去给实验室买花。我一再表示，我没有什么力气拎不动，建议他找一个男生一起去，但是他坚持说找不到其他人，不用我拎着，一定逼着我去，让我赶紧上车跟他走，不用等其他人。（我后来和同学们交流，当时至少还有一位同学明确表示想一起去，被洪森炼拒绝。）最后他开了大概半小时车，带我到了一个很偏僻的花市（事后我查阅地图，确定是海淀区五环外的金地花卉大观园，与学校距离达13公里）。我跟着他在花市里走的时候，他多次装作很自然，其实一点也不自然的姿态用手搂我的腰和肩，我拼命躲闪，努力走在他的前面或后面与他拉开距离，他还是不断地向我靠近。我屡屡大声说，“老师，我们要买什么呢？”等话，不断大声喊他“老师”让周围的摊主和路人听见，他才有所收敛。直到买完花回到实验室，洪森炼都难掩其兴奋神色，实验室的同学都有察觉。
5.要求我跟他单独爬山洪森炼多次要求我陪他去凤凰岭（与学校距离达35公里）爬山，我一直拒绝，最终还是跟他在工作日去了两次（分别是2022年2月24日和2022年3月10）。每一次，他都借口说已经叫了实验室的另一位同学M（男生，化名），但是他有事去不了，以创造只有我一个人跟他去的结果。但我后来问了M，事实上洪森炼从来没有叫过他。每次开车他都要求我坐在副驾驶的位置，他说坐在后排就是不尊重他。而且他曾要求帮我系安全带，在我的强烈阻止下没有得逞。有一回，他要求我在凤凰岭山下农家乐跟他吃晚饭，当时天色已晚，已经快六点了，而且凤凰岭位于北京郊外，极其偏僻。我坚持说我已经约了同学，同学已经在等我吃晚饭了，他才作罢。每次爬山，洪森炼都要求走凤凰岭南线，南线极其崎岖荒僻，游客罕至，常常见不到人。洪森炼借口山路崎岖，总是要强行拉我的手。我十分害怕，每次爬山途中，都极尽全身之力拼命快爬，以求早点下山，并且尽量与洪拉开距离。我觉得洪把我带去凤凰岭这种荒僻的地方，有消灭罪证之嫌。如果说我在当时的情境下真的发生了什么，谁来保证我的安全呢？谁来维护我的权益呢？

另外，我有2022年6月12日洪森炼本人的谈话录音，他本人说确有此事。但是他在谈话中，首先隐去了他对我骚扰的情节（包括系安全带、强行拉手等），并捏造爬山缘由，借口我长期失眠需要锻炼。但是事实上，洪森炼的长期骚扰和欺凌，正是造成我每晚失眠、甚至整宿都无法入睡的原因。【6.12洪森炼自述（爬山）01、6.12洪森炼自述（爬山）02、6.12洪森炼自述（爬山）03、6.12洪森炼自述（爬山）04】

**Comment by SakuraLaurel** [comment]
加油

**Comment by Zn-L** [comment]
jiayou

**Comment by nemo434** [comment]
加油

**Comment by kisinin** [comment]
能不能标注一些关键性的证据啊，刚刚听了个录音，听不出个什么证据啊

**Comment by CarleySky** [comment]
加油！

**Comment by chaoszh** [comment]
upupup

**Comment by a-xiba** [comment]
建议不要把希望只放在bd的纪委！！他们肯定优先考虑的是学校！
生命与学位相比，肯定是生命更重要啊。做好斗争到底的心理准备。（能保则保学位，保不住可以再考）因为她现在唯一的顾忌就是自己现在的学位，抛开这个还有什么好怕的。
大不了重新申请个学校读博。
1.撕破脸皮使劲报警！ 2.各个机关（社区，市长热线，妇联帮助，）实名举报。
要有勇气斗争，不要怕失去什么，也没有什么好失去的。不要因为人渣而让自己难受，应该让他收到应有的惩罚。
不要委屈自己，大胆一点去保护自己的，不要再顾忌bd的名声，这和你没关系，你只负责撕破脸皮好好保护自己！

**Comment by a-xiba** [comment]
之所以这么委屈就是因为害怕丢掉学位！！
学位没了还能再申请其他学校！！！！！
与其这么难受不去放下自己的顾忌，斗争到底！！要让他付出代价

**Comment by Gallo13th** [comment]
洪森炼真是跟谢灿学了看家本事。
这件事情不必有来自痛苦回忆以外的压力。顶住这些压力，然后去寻找证据，去把事情闹大。要相信，北大以外的单位来调查北大的时候，不会像北大自查那么和稀泥。别忘了去年巡视组走完一圈之后给各大学校打的评语，何其不留情。
只是有了那么多次破事，原楼主居然既不撕破脸又不暗中采证。天真的有点可爱了。。这也导致解决问题的方法就必须是闹大。以任何一个学校的行政来说，没有证据的事情，就只看影响。事情闹大了，政府介入了，舆论爆炸了，他们就必须要想老师施压。
只是委屈了原楼主，即使导师被逼迫道歉，甚至停职离职，也未必就意味着自己的冤屈能被澄清，可能还要面对很长时间的阴影。

**Comment by Matthiola** [comment]
学妹，你很勇敢，我相信你。请不要放弃。

**Comment by angrysnail** [comment]
github都负责这事了，还有fork的，服了。
要是这个洪sir有事，办他！不影响他人，垃圾也就垃圾了，人家不愿意还强行，这就低劣了。
长的挺周正的，学历也好，可惜当了老师，人渣界的损失。
用钱出校解决不好么，非要用前程来要挟自己学生，这也太有违良俗了。

**Comment by handforever** [comment]
必须upup

**Comment by handforever** [comment]
> 学妹，你很勇敢，我相信你。请不要放弃。
upup

**Comment by peltorx5a** [comment]
想到北医对偷拍女浴室女卫生间事件的处理，此事恐怕也会随着时间淹没吧。

**Comment by liulangdezidan** [comment]
加油，祝福你

**Comment by yhp-hub** [comment]
加油

**Comment by BaiWenchao** [comment]
加油

**Comment by rivershop** [comment]
加油

**Comment by YuanJ-yj** [comment]
加油，好好生活。你还有很多美好没有遇到！

**Comment by HuaFen9** [comment]
加油、顶住

**Comment by txw-lab** [comment]
气死我了，给这狗东西制了

**Comment by Erchoc** [comment]
加油没用，建议实名举报；但目前看 repo 中提到的文字录音等材料杂乱无章，很多都不能算做证据，需要梳理清楚。

**Comment by santushenfansgithub** [comment]
加油，很多北大同学站在你的身后的。

**Comment by 430666999** [comment]
看了几张洪的聊天截图，首先这个聊天应该是删减过的？并没有发现什么问题 ，其次受害者应该是有男友的，为什么没有发起纷争，这只是我觉得有点疑点的地方，证据不是用嘴说的，如果情况属实那么我希望你们不要放弃，多抓出一些证据，特别是录像和行为期间的录音，DNA，因为其他的都很难作为证据。

**Comment by aoliluckin** [comment]
万字长文不如一段录音等实质性证据，如果事情是真的，那这位导师就去坐牢。如果是诬告，不要让诬告成本那么低。

**Comment by aoliluckin** [comment]
录音剪得支离破碎，听不出什么实质性内容

**Comment by minyez** [comment]
re 楼上。建议整理一下录音时间戳，便于整合。看一下录音程序提供的详细即可，应该不难。

**Comment by lydialin92** [comment]
希望同一研究组里的其他同学能够勇敢的为你们的同学，未来的学弟学妹，站出来发声，无论是证实或证伪，都对真相有帮助。怕被打击报复，可以通过有良知的第三方，比如律师，记者发声，或者哪怕是在这里匿名发个帖子，只要是事实，都值得倾听。

**Comment by Xue504** [comment]
加油！好好整理材料，这波能赢！发声的时候就赢了，是人格的胜利！姐妹们加油！

**Comment by Xue504** [comment]
还有就是看一下洪森炼的国籍，我知道的有些搞科研的会换国籍，然后用各种吓唬人的方式来为自己开脱
