### ISSUE TITLE
可以发一份完整版的录音吗？

### ISSUE THREAD

**Issue by zzMiao123** [PoaceaeTriticum/Exposure_HongSenlian#5]
录音片段太细碎了，建议再放一个完整版，然后语音转成纯对话放出来，现在的形式看起来比较累，不方便其它人了解

**Comment by kisinin** [comment]
> 赞同

**Comment by jiangjiangyi** [comment]
同意 这里有来自网友的提醒
1.她提到经常深夜打她电话，这个她可以去营业厅打通话记录（佐证不正常时间常常接到电话）
2.拿到这个以后，把这些陈述加上电话记录发到微博@相关单位
3.微信记录是可以复原的，公安是可以的，但是估计没有一定的关注度比较难做到。如果她很肯定微信记录里面也有相关有力的证据，可以咨询下是否可以申请到
“可以恢复，公安部门有能力找到您删除的同对方微信聊天记录。不过，只有在涉及刑事侦查证据，有必要恢复时，公安部门才会恢复此记录，多久的都可以恢复。”
