### ISSUE TITLE
同意 这里有来自网友的提醒

### ISSUE THREAD

**Issue by jiangjiangyi** [PoaceaeTriticum/Exposure_HongSenlian#6]
同意 这里有来自网友的提醒
1.她提到经常深夜打她电话，这个她可以去营业厅打通话记录（佐证不正常时间常常接到电话）
2.拿到这个以后，把这些陈述加上电话记录发到微博@相关单位
3.微信记录是可以复原的，公安是可以的，但是估计没有一定的关注度比较难做到。如果她很肯定微信记录里面也有相关有力的证据，可以咨询下是否可以申请到
“可以恢复，公安部门有能力找到您删除的同对方微信聊天记录。不过，只有在涉及刑事侦查证据，有必要恢复时，公安部门才会恢复此记录，多久的都可以恢复。”

_Originally posted by @jiangjiangyi in https://github.com/PoaceaeTriticum/Exposure_HongSenlian/issues/5#issuecomment-1179763589_

**Comment by jiangjiangyi** [comment]
拿到通话记录可以告诉学校，你们的男导师是不是都这样大晚上给女学生打电话。学校的主管部门会重视的。拿到证据以后，话不要多说就这么一个反问就能足够重视了。扳不扳倒另外一回事儿，至少学业上有机会保住，能有谈判的筹码。
另外，第一步完成了以后，可以告诉对方或者学校，让他不要这么嚣张，我已经证明了一步，如果我花花力气证明第二步并不是不可能，微信记录是可以恢复的。
讲真，没有实质性的侵犯，猥琐又没有直接证据，通话记录是间接证据，除非微信记录有实锤，不然这种情况更多的考虑是利用好有限的证据以及合理的舆论力量让自己不那么被动，让对方的嚣张气焰得到一定的打压
剩下就是好好完成学业，好好生活下去。

**Comment by David-JA** [comment]
支持，希望同学能好好生活下去，躲过这一劫

**Comment by BJWang-ant** [comment]
支持，同学，好好生活下去，不要被这种人渣影响自己的人生。这种畜生，会不得好死的

**Comment by AmilyFox** [comment]
我是当事人的朋友，非常感谢各位朋友的建议和支持！
